create table CUSTOMERS
(
  id           number generated by default as identity,
  name         NVARCHAR2(100),
  surname      NVARCHAR2(100),
  age          number,       
  phone_number NVARCHAR2(11),
  CONSTRAINT customers_pk PRIMARY KEY(id)
);

