create table CUSTOMERS
(
  id           number generated by default as identity,
  name         NVARCHAR2(500),
  surname      NVARCHAR2(500),
  age          NVARCHAR2(500),       
  phone_number NVARCHAR2(500),
  CONSTRAINT customers_pk PRIMARY KEY(id)
);

