create table ORDERS
(
  id           number generated by default as identity,
  dates        DATE,
  product_name NVARCHAR2(500),       
  amount       number,
  customer_id  number,
  CONSTRAINT orders_pk PRIMARY KEY(id),
  FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id)
);

